spring:
  application:
    name: spotify-api-client-test
server:
  port: 8080

spotify:
  clientId: 772da04c86ef487b887319b1792b8f4d
  clientSecret: e27d7419cb7e4d18b63e6e35854b9d05
  redirectUrl: http://localhost:8080/redirect

logging:
  level:
    root: info
    com.victorlh.spotify.apiclient: trace